### ISSUE TITLE
vue/attribute-hyphenation

### ISSUE THREAD

**Issue by BITRU** [frikinside/vue3-simple-typeahead#16]
eslit rule privent naming atributes like this 
`:minInputLength=
:itemProjection=
`

https://eslint.vuejs.org/rules/attribute-hyphenation.html

So it lint auto fix problem it can make module fail and long chase for error  to user. 

need to add in eslint
  "vue/attribute-hyphenation": ["error", "always", {
    "ignore": []
  }]

So, can you change naming for convention purposes. 

Love your work!

**Comment by frikinside** [comment]
Thanks for your support mate!
Yeah, linters could get in the way sometimes, but instead of disabling it, you could use kebab-case instead of camel case.
If you notice in the "Props" section of the readme says the following:
![image](https://user-images.githubusercontent.com/13966372/176979171-36b64d20-2de6-461a-bde2-11eb5b0dd4a5.png)
Maybe you could try that!

**Comment by BITRU** [comment]
my false. Thanks for your work!
