### ISSUE TITLE
Question: setting focus to the input field on page loading

### ISSUE THREAD

**Issue by Kar1s** [frikinside/vue3-simple-typeahead#17]
Hello,

how can I direct the focus to the list on page loading, to make it ready to take the keyboard's input?

for example, the function below is for a "clear input" button that works (does clear the field), but I can't make it so I don't have to go click on the input field again to be able to write.

    resetInput() {
      this.$refs["inputarea"].input = "";
      this.data.selection = null;
      this.$refs["inputarea"].$el.focus(); // this line doesn't do much, also tried $refs[].input.focus() and $refs[].focus() 
    },
    
many thanks in advance :)

**Comment by frikinside** [comment]
I would say that `this.$refs["inputarea"].focus();` should work.
I'll try to make a few tests and replicate the issue.

**Comment by Kar1s** [comment]
this was my first thought, but this.$refs["inputarea"].focus(); give the following error in console; 
 Uncaught TypeError: this.$refs.inputarea.focus is not a function 

my full code 
`<div v-if="dataloaded_bool">
          <div align="center">
            <img :src="`data:image/jpg;base64,${Ximg_64}`" class="fit-image" />
          </div>

          <div>
            <vue3-simple-typeahead 
              align="center"
              ref="inputarea"
              :items="classlist"
              :placeholder="options.placeholder"
              @selectItem="onSubmit"
              @onInput="onInput"
              @onBlur="onBlur"
              :minInputLength="options.minInputLength"
            >
            </vue3-simple-typeahead>
            <p>&nbsp;</p>
            <button
              type="button"
              class="btn btn-secondary"
              align="right"
              @click="resetInput"
            >
              clear
            </button>
          </div>
        </div>
      </div>
      
      and later in methods:
      resetInput() {
  this.$refs["inputarea"].input = "";
  this.data.selection = null;
  this.$refs["inputarea"].focus();  
},
      `
      
      the whole typeahead  is a copy of the demo, except it is placed inside a v-if so it shows only after finishing loading some data from the backend.. but even if I put it outside the v-if it still gives the same error

**Comment by frikinside** [comment]
Hi, I was looking into this and honestly have way more problems than I thought.
For some reason I couldn't make  `.focus()` method to work in several browsers (Opera, Chrome, Edge) in any page I try. Even with something as simple as `document.getElementbyId('isOfelement').focus()` wouldn't work. 
But maybe that's a problem on my end, because doesn't event work outside this component or Vue3, maybe something change and `.focus()` isn't the way to do it anymore or I have trouble with it because of problems with my own environtment.

So if the `.focus()` doesn't work to you, try using something simple like I describe in the previous parragraph and tell me your results.
----------------------------------------------------
Despite all of that, and assuming that `.focus()` problem is only mine, I check you issue and realize that the ref you are using are pointing to the component and not the input that the component use. That's why you could clear the input of the component the way you did.

To solve this I added a few methods to play with the ref component and the input control:
| Method                      | Signature                       | Description                                                      |
| :-------------------------- | :------------------------------ | :--------------------------------------------------------------- |
| [`clearInput`](#clearInput) | `function (): void`             | Clean the input with an empty string `''`                        |
| [`focusInput`](#focusInput) | `function (): void`             | Trigger focus on the input and called `onFocus` event handler    |
| [`blurInput`](#blurInput)   | `function (): void`             | Trigger blur on the input and called `onBlur` event handler      |
| [`getInput`](#getInput)     | `function (): HTMLInputElement` | Return the `HTMLInputElement` corresponding to the input control |

Use this methods using the ref on the component:
```html
<vue3-simple-typeahead ref="inputarea"> </vue3-simple-typeahead>
```

```javascript
{
	this.$refs.inputarea;
}
```

In code, `this.$refs.inputarea` would have access to the methods above.
So using you example and the new methods you could do it in several ways:

Using the `clearInput` method.
```javascript
resetInput() {
    this.$refs.inputarea.clearInput();
  }
```

Changing the value and the triggering the `focusInput`.
```javascript
resetInput() {
    this.$refs.inputarea.input = '';
    this.$refs.inputarea.focusInput();
  }
```

Or using the `.focus()` yourself.
```javascript
resetInput() {
    this.$refs.inputarea.input = '';
    this.$refs.inputarea.getInput().focus();
  }
```

**Comment by Kar1s** [comment]
Thank you very much, I tried the new release, and it works great!

**Comment by frikinside** [comment]
Excellent! Which method do you use?

**Comment by Kar1s** [comment]
both variations of input focus worked fine; ~.focusInput(); as well as ~.getInput().focus();  😄

**Comment by frikinside** [comment]
Great! Thanks for taking your time to answer
