### ISSUE TITLE
feature(?): allow input of something not on list.

### ISSUE THREAD

**Issue by shaunc** [frikinside/vue3-simple-typeahead#19]
I would like to have a selection list for existing values, but also allow entry of entirely new value on blur via tab or enter. 

Is this possible?
It seems that if I type anything that is a prefix of existing value, then on blur I get first selection rather than what I typed.

**Comment by frikinside** [comment]
Yes this happens when you lost focus via <kbd>TAB</kbd>. If you lost focus clicking away dont.
If you look at the readme, in the navigation section it reads the following:
| <kbd>TAB</kbd>   | Choose the current element selection                               |

I understand that this could be not a desirable behaviour so I'll make the selection on tab optional.

I'll fix it as soon as I can.

**Comment by frikinside** [comment]
I added a new prop: `selectOnTab`, a Boolean with a default value of `true`.
If you set it a `false` it would not select the item on <kbd>TAB<kbd>
