### ISSUE TITLE
Open item list on focus

### ISSUE THREAD

**Issue by aanders77** [frikinside/vue3-simple-typeahead#7]
Hi,
How do I make the item list open when the input gets focus? (Like you're doing in the second demo).
Btw you should add the relevant code for each demo :)

Regards, Anders

**Comment by aanders77** [comment]
Hi again,
This plugin apparently doesn't like being wrapped in <ion-item>. The option list disappears, and there's no auto-open when focused. If moving it out of the ion-item, it works as expected.

**Comment by frikinside** [comment]
> Hi, How do I make the item list open when the input gets focus? (Like you're doing in the second demo). 

The component response for the focus input event. But in order to show the suggestion list on focus first the input length should meet the min established with the `minInputLength` prop.

> Btw you should add the relevant code for each demo :)

There it is! 
[vue3-simple-typeahead-demo repository](https://github.com/frikinside/vue3-simple-typeahead-demo)
I add it to the repo readme too.

> Hi again, This plugin apparently doesn't like being wrapped in . The option list disappears, and there's no auto-open when focused. If moving it out of the ion-item, it works as expected.

Maybe there's some conflicting styles? Can you provide an example so I can check it out?

**Comment by aanders77** [comment]
Thank you @frikinside ! I tried creating a codesandbox to show the problem, but for some reason it fails as soon as the plugin is activated. I don't have time right now to find out why. https://codesandbox.io/s/misty-night-brmw5?file=/src/Home.vue

**Comment by frikinside** [comment]
Thanks for provide a full example and taking time to explain the issue.

I see, the error you are getting in codesandbox is "`(0 , $csb__vue.createElementVNode) is not a function`" right?
I check it and everything seems fine, I'm not sure what the problem is :/

But for what I can understand, that could be a problem with codesandbox and you are using the component in another environment without errors, correct?

I'll try to replicate in local the same sample you give me. Using the ionic framework and put inside a _<ion-item>_ the component and see how it behaves.
Unfortunately I don't have much free time recently so I'm not sure when I can do it. Sorry in advance.

Meanwhile, let me know with any progress or drawback with this issue!

**Comment by aanders77** [comment]
Yes, that is correct. Ok, thanks for the help so far.

**Comment by frikinside** [comment]
I check this issue and make a simple test in local.
And I get exactly the behaviour you were telling earlier. I dig a bit more in the DOM and styles and te component is working correctly but the ion container is cutting the component. The component is there, but hidden because of this.

And that's because the 'simple-typeahead-list' has position absolute with doesn't work properly with ion-content.
If you override the styles and set position as 'static' the list shows without problems (making the list expand the height of the element) and behaves correctly.

I'm not familiar with ionic so I'm not sure how to solve that for you but a quick search shows a few people strugglin with absolute positioning content inside ion too: 
https://stackoverflow.com/questions/27251866/ionic-framework-position-absolute-with-bottom-in-doesnt-work
https://stackoverflow.com/questions/54244706/ion-item-cuts-off-an-absolute-positioned-element/54245023

You could override the styles to make it work for your case. I hope that helps you solving the issue!

**Comment by aanders77** [comment]
Thank you for looking into this. I will try 'static' 👍
